name: cs231n-py27
channels:
  - conda-forge
  - default
dependencies:
  - python=2.7
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - cython
  - jupyter
  - nb_conda_kernels
  - Cython=0.23.4
  - Pillow
